### PR TITLE
Completed the OpenAPI QuickStart

### PR DESCRIPTION
**Pull request by bradygaster**
@LadyNaggaga let me know if this is the right style you'd hoped for in terms of TOC placement and so forth. Definitely do not merge yet, as there's a lot of work to be done, but just wanted to make sure this represents the approach you'd hoped I'd take with placing the article in the TOC and the H1/H2/H3's. :) Let me know if you have any tweaks you'd like me to make to this approach and I'll adjust and finish the content. 

Feel free to close this PR once you let me know if this is the desired approach, and I'll finish up the content ASAP.

### CODE REVIEW

**Review by LadyNaggaga — CHANGES_REQUESTED** [review]
Could you please move the  guide/openapi do to guide section please?

**Comment by davidfowl** [comment]
@bradygaster take a look here as well https://gist.github.com/davidfowl/ff1addd02d239d2d26f4648a06158727#open-apiswagger. I want to make sure I cover all of the methods that can influence the open API description. I'm sure I'm missing some

**Comment by bradygaster** [comment]
@LadyNaggaga i've moved this over per your request and finished up what i think is a concise OpenAPI quickstart. This is ready for your review and merge. Thanks so much!

**Comment by bradygaster** [comment]
> @bradygaster take a look here as well https://gist.github.com/davidfowl/ff1addd02d239d2d26f4648a06158727#open-apiswagger. I want to make sure I cover all of the methods that can influence the open API description. I'm sure I'm missing some

Did you see the doc @captainsafia was working on? I'd argue all of her content could be brought in to your doc, too. That's a fantastic doc. Kitchen sink!

Here's the link to Safia's content: https://github.com/Minimal-APIs/minimal-apis.github.io/issues/36

**Comment by bradygaster** [comment]
Last update on this - i've added @captainsafia's content from the issue and applied a teensy bit of wordsmithery to it. Let me know if any of you have anything to add (or feel free to update the PR, i welcome any tweaks on this).

**Comment by LadyNaggaga** [comment]
This so dope!!!!  Thank you

**Pull request merged**
